### ISSUE TITLE
Can't compile on windows

### ISSUE THREAD

**Issue by Arch-Mina** [Dahrkael/PhysFS-AES#1]
Hello,

Every time i try to compile on windows i get this error 
`Error  LNK2019 unresolved external symbol _fcrypt_init referenced in function _zip_get_file_handle physfs`
`Error  LNK2019 unresolved external symbol _fcrypt_decrypt referenced in function _readui8  physfs`

i get this error on both visual studio 2013,2015
any idea how to fix it?

Thanks in advance

**Comment by Dahrkael** [comment]
Hello,
I suppose you fixed it since you closed the issue, but anyway for other people with the same problem in the future.
Make sure you have the files inside the AES folder in the project so they get compiled, this way those error wont appear
